### ISSUE TITLE
TFM3.2.2 not creat database in msfs2020 1.30.12.0

### ISSUE THREAD

**Issue by crportes** [talking-flight-monitor/talking-flight-monitor#165]
halo. in this case, i'm using tfm with msfs2020, and a db for tfm is not created using boton to create in settings.  TFM log is atached.
[tfm.log](https://github.com/talking-flight-monitor/talking-flight-monitor/files/10771953/tfm.log)

**Comment by ajborka** [comment]
You need to follow the steps below. Chances are, you need to run makerunways before creating the database.

 

*	Create an empty folder to hold the MSFS makerunways output.
*	Download makerunways from fsuipc.com
*	Extract makerunways.exe from the .zip download and put it in the folder created above.
*	Right click on makerunways.exe and run it as administrator.
*	Go to the next step when everything generated ok.
*	Start MSFS
*	* Load an aircraft and enter the cockpit.
*	Start TFM and go to settings
*	Go to airports database section.
*	Assign the folder created above to the MSFS database path.
*	* Press OK to save settings.
*	Return to TFM settings
*	Go to the airports database section.
*	Press the build database button.

You should get a confirmation that everything worked.

**Comment by crportes** [comment]
Halo! successfull! Thanks for yor instructions.

Em sex., 17 de fev. de 2023 às 19:33, Andy Borka ***@***.***>
escreveu:

**Comment by marrie** [comment]
I did all of this and got the continue and details  dialogue. I'm sitting in a pmdg  at KLAS. Here is the trace message. I did run mkrwy file as admin yesterday when the airac cycle got updated at the time of this comment. I did update msfs though  a few minutges before Running this database compile, so maybe something broke after the msfs update. I can refollow the steps and try and compile, again. thanks

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
FSUIPC.FSUIPCException: FSUIPC Error #65541: FSUIPC_MAKERUNWAYS_FILES_MISSING. The MakeRunways output files could not be found. Please check/set the MakeRunways path
   at FSUIPC.AirportsDatabase.<RebuildDatabaseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FSUIPC.AirportsDatabase.<RebuildDatabaseAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at tfm.ctlDatabases.<rebuildAirportsDatabaseButton_Click>d__5.MoveNext() in C:\projects\talking-flight-monitor\source\Settings panels\ctlDatabases.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9105.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
tfm
    Assembly Version: 23.2.0.0
    Win32 Version: 23.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/tfm.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9065.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: 5.1.1.1522
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/NLog.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9115.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
TolkDotNet
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/TolkDotNet.DLL
----------------------------------------
System.Speech
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Speech/v4.0_4.0.0.0__31bf3856ad364e35/System.Speech.dll
----------------------------------------
fsuipcClient
    Assembly Version: 3.3.2.402
    Win32 Version: 3.3.2.402
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/fsuipcClient.DLL
----------------------------------------
NGeoNames
    Assembly Version: 1.5.1.0
    Win32 Version: 1.5.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/NGeoNames.DLL
----------------------------------------
NHotkey.WindowsForms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/NHotkey.WindowsForms.DLL
----------------------------------------
NHotkey
    Assembly Version: 2.0.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/NHotkey.DLL
----------------------------------------
KdTreeLib
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/KdTreeLib.DLL
----------------------------------------
NAudio.WinMM
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/NAudio.WinMM.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
NAudio.Core
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/NAudio.Core.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.117.0
    Win32 Version: 1.0.117.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9110.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/Newtonsoft.Json.DLL
----------------------------------------
BingMapsSDSToolkit
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Talking%20Flight%20Monitor/BingMapsSDSToolkit.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by marrie** [comment]
update. I  forgot I had just downloaded world update 12 which just came out today, and had to run mkrwy again. that never actually crossed my mind. I believe the datgabase was a success. Cool. all is well, and lesson learned. Thanks.

**Comment by ajborka** [comment]
This is fixed.
