### ISSUE TITLE
feature request: be able to access the second fmc 

### ISSUE THREAD

**Issue by blindflightsimmer** [talking-flight-monitor/talking-flight-monitor#168]
Now that shared cockpit is usable through your controls, would be cool to enable access to the second cdu, perhaps through a hotkey to switch between them when the fmc window is in view, so that both captain and first officer can bring up different pages if they want to.

**Comment by jfayre** [comment]
Thanks! This should be really easy to add. 

 

 

From: blindflightsimmer ***@***.***> 
Sent: Friday, July 7, 2023 8:07 AM
To: talking-flight-monitor/talking-flight-monitor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [talking-flight-monitor/talking-flight-monitor] feature request: be able to access the second fmc (Issue #168)

 

Now that shared cockpit is usable through your controls, would be cool to enable access to the second cdu, perhaps through a hotkey to switch between them when the fmc window is in view, so that both captain and first officer can bring up different pages if they want to.

**Comment by ajborka** [comment]
Should be easy to add a second one. Will put it on the todo list.

 

 

From: blindflightsimmer ***@***.***> 
Sent: Friday, July 7, 2023 8:07 AM
To: talking-flight-monitor/talking-flight-monitor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [talking-flight-monitor/talking-flight-monitor] feature request: be able to access the second fmc (Issue #168)

 

Now that shared cockpit is usable through your controls, would be cool to enable access to the second cdu, perhaps through a hotkey to switch between them when the fmc window is in view, so that both captain and first officer can bring up different pages if they want to.

**Comment by BviPilots** [comment]
That would be a really good feature to have. ALso here is a page that
gives you a run down on setting up, and what the different types of
connections mean. Hope this might help some.
https://docs.yourcontrols.one/running

**Comment by ajborka** [comment]
This is complete.
