### ISSUE TITLE
new feature request: sids/stars spoken

### ISSUE THREAD

**Issue by armstrong25** [talking-flight-monitor/talking-flight-monitor#20]
I would like to see when you are on a sid or a star as you come to the waypoint on that sid or star, I would like to hear the altitude restriction and speed read out.  **Describe the bug**

**To Reproduce**

**Expected behavior**

**additional information
 - OS: [e.g. Windows 10]
 - TFM version: 
 - Flight simulator in use: 

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.

**Comment by marrie** [comment]
This could apply to any way point on the list, per my think out loud. the layout could look like this.


| name | distance | speed | alt |
| ----- | ----- | ----- | ----- |
| wpnes | 500nm | 290kts | 32000
| wptsa | 50nm | 250 | 6000 |

Bad example but hopefully the point is clear.

**Comment by marrie** [comment]
I forgot to add baring, but the rest of the table should be correct, and all waypoints have an alt restriction in a way, (see your flight plan) I move that all waypoints whether it is sid, star, appr, or on route should be able to be narrated.

**Comment by ajborka** [comment]
I will look into this when I start flight planning stages of development. We might not have the ability to send everything to the screen reader when pressing ]w, but we can have the details outlined in each waypoint of the flight plan. The basic format when pressing ]w might look like the following:

next waypoint: star, soxx5, distance 29.4kn, time left 15:34, alt 9000, speed 230kn.

My research on adding sid/star waypoints resulted in some interesting findings that explain why sid/stars aren't included in the ]w announcement of the next waypoint. Stay tuned to the next podcast because I am going to explain it then.

**Comment by ajborka** [comment]
This is stale and needs further/recent justification to implement for freeware aircraft.
