### ISSUE TITLE
Feature Request: Set Waypoint Altitudes

### ISSUE THREAD

**Issue by trodick** [talking-flight-monitor/talking-flight-monitor#23]
In the flight plan/AP management system, can we please have the ability to set waypoint altitudes (either crossing or altitude after)? That way we can comply with altitude crossing restrictions, or program the system to handle step climbs correctly.

**Comment by ajborka** [comment]
@trodick  this is already at the front of the flight planning stage after initial support has been tested. I have plans for altitude changes and speed changes. Both for cross waypoint at [speed/altitude], and set altitude/speed after this waypoint. EX: on a waypoint, you can cross at 4500ft at 200kn. Once passed the waypoint, descend to 1000ft and hold a speed of 160kn. The next waypoint should tell you what to do since this example assumes you are somewhere in a star.

**Comment by ajborka** [comment]
This is stale and needs further/recent justification to implement for freeware aircraft.
